fileUrl <- 'https://archive.ics.uci.edu/ml/machine-learning-databases/00235/household_power_consumption.zip'
download.file(fileUrl, destfile ="./HouseholdPower")
unzip("./HouseholdPower")
HHPower <-read.table(unzip("./HouseholdPower"), na.strings = "?", header = TRUE, sep = ";")
head(HHPower)
str(HHPower)
HHPower <- subset(HHPower, Date == "1/2/2007" | Date == "2/2/2007")
HHPower[, c(3:9)] <- sapply(HHPower[, c(3:9)], as.character)
HHPower[, c(3:9)] <- sapply(HHPower[, c(3:9)], as.numeric)
HHPower$Date <-as.Date(HHPower$Date, format = "%d/%m/%Y")
HHPower <- transform(HHPower, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
png('rplot3.png', width= 480, height = 480)
with(HHPower,plot(timestamp, Sub_metering_1, type="l", ylim = c(0,30), xlab="", ylab="Energy Sub metering"))
lines(HHPower$timestamp,HHPower$Sub_metering_2,col="red")
lines(HHPower$timestamp,HHPower$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.off()
