fileUrl <- 'https://archive.ics.uci.edu/ml/machine-learning-databases/00235/household_power_consumption.zip'
download.file(fileUrl, destfile ="./HouseholdPower")
unzip("./HouseholdPower")
HHPower <-read.table(unzip("./HouseholdPower"), na.strings = "?", header = TRUE, sep = ";")
head(HHPower)
str(HHPower)
HHPower <- subset(HHPower, Date == "1/2/2007" | Date == "2/2/2007")
HHPower[, c(3:9)] <- sapply(HHPower[, c(3:9)], as.character)
HHPower[, c(3:9)] <- sapply(HHPower[, c(3:9)], as.numeric)
HHPower$Date <-as.Date(HHPower$Date, format = "%d/%m/%Y")
HHPower <- transform(HHPower, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
png('rplot2.png', width= 480, height = 480)
plot(HHPower$timestamp, HHPower$Global_active_power, type="l", ylim = c(0,6), xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
